<dec f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='56' type='void boost::contract::exception::~exception()'/>
<def f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='28' type='void boost::contract::exception::~exception()'/>
<ovr f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='43' c='_ZN5boost8contract23bad_virtual_result_castD1Ev'/>
<ovr f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='62' c='_ZN5boost8contract17assertion_failureD1Ev'/>
<doc f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='51'>/**
    Destruct this object.

    @b Throws: This is declared @c noexcept (or @c throw() before C++11).
    */</doc>
<doc f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='56'>/** @cond */</doc>
<doc f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='56'>/** @endcond */</doc>
