<def f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='797' ll='805' type='const boost::contract::from_failure_handler &amp; boost::contract::set_entry_invariant_failure(const boost::contract::from_failure_handler &amp; f)'/>
<dec f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='485' type='const boost::contract::from_failure_handler &amp; boost::contract::set_entry_invariant_failure(const boost::contract::from_failure_handler &amp; f)'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/detail/inlined/core/exception.hpp' l='494' u='c' c='_ZN5boost8contract21set_invariant_failureERKNS_8functionIFvNS0_4fromEEEE'/>
<doc f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='780'>/**
Set failure handler for class invariants at entry.

Set a new failure handler and returns it.

@b Throws: This is declared @c noexcept (or @c throw() before C++11).

@param f New failure handler functor to set.

@return Same failure handler functor @p f passed as parameter (e.g., for
        concatenating function calls).

@see    @RefSect{advanced.throw_on_failures__and__noexcept__, Throw on Failure},
        @RefSect{tutorial.class_invariants, Class Invariants},
        @RefSect{extras.volatile_public_functions,
        Volatile Public Functions}
*/</doc>
