<dec f='boost-1.85.0/libs/fiber/include/boost/fiber/exceptions.hpp' l='68' type='const std::error_category &amp; boost::fibers::future_category()'/>
<use f='boost-1.85.0/libs/fiber/include/boost/fiber/exceptions.hpp' l='80' u='c' c='_ZSt15make_error_codeN5boost6fibers11future_errcE'/>
<use f='boost-1.85.0/libs/fiber/include/boost/fiber/exceptions.hpp' l='85' u='c' c='_ZSt20make_error_conditionN5boost6fibers11future_errcE'/>
<use f='boost-1.85.0/libs/fiber/src/future.cpp' l='23' u='c' c='_ZNK5boost6fibers21future_error_category23default_error_conditionEi'/>
<use f='boost-1.85.0/libs/fiber/src/future.cpp' l='27' u='c' c='_ZNK5boost6fibers21future_error_category23default_error_conditionEi'/>
<use f='boost-1.85.0/libs/fiber/src/future.cpp' l='31' u='c' c='_ZNK5boost6fibers21future_error_category23default_error_conditionEi'/>
<use f='boost-1.85.0/libs/fiber/src/future.cpp' l='36' u='c' c='_ZNK5boost6fibers21future_error_category23default_error_conditionEi'/>
<def f='boost-1.85.0/libs/fiber/src/future.cpp' l='66' ll='69' type='const std::error_category &amp; boost::fibers::future_category()'/>
