<def f='boost-1.85.0/libs/thread/include/boost/thread/futures/future_error_code.hpp' l='45' ll='50' type='boost::system::error_code boost::system::make_error_code(boost::future_errc e)'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/futures/future_error.hpp' l='42' u='c' c='_ZN5boost20future_uninitializedC1Ev'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/futures/future_error.hpp' l='50' u='c' c='_ZN5boost14broken_promiseC1Ev'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/futures/future_error.hpp' l='58' u='c' c='_ZN5boost24future_already_retrievedC1Ev'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/futures/future_error.hpp' l='66' u='c' c='_ZN5boost25promise_already_satisfiedC1Ev'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/futures/future_error.hpp' l='75' u='c' c='_ZN5boost20task_already_startedC1Ev'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/futures/future_error.hpp' l='84' u='c' c='_ZN5boost10task_movedC1Ev'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/futures/future_error.hpp' l='93' u='c' c='_ZN5boost13promise_movedC1Ev'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/future.hpp' l='3746' u='c' c='_ZN5boost13packaged_task5resetEv'/>
