<def f='boost-1.85.0/libs/fiber/include/boost/fiber/exceptions.hpp' l='95' ll='97' type='void boost::fibers::future_error::future_error(std::error_code ec)'/>
<use f='boost-1.85.0/libs/fiber/include/boost/fiber/exceptions.hpp' l='103' u='c' c='_ZN5boost6fibers20future_uninitializedC1Ev'/>
<use f='boost-1.85.0/libs/fiber/include/boost/fiber/exceptions.hpp' l='110' u='c' c='_ZN5boost6fibers24future_already_retrievedC1Ev'/>
<use f='boost-1.85.0/libs/fiber/include/boost/fiber/exceptions.hpp' l='117' u='c' c='_ZN5boost6fibers14broken_promiseC1Ev'/>
<use f='boost-1.85.0/libs/fiber/include/boost/fiber/exceptions.hpp' l='124' u='c' c='_ZN5boost6fibers25promise_already_satisfiedC1Ev'/>
<use f='boost-1.85.0/libs/fiber/include/boost/fiber/exceptions.hpp' l='131' u='c' c='_ZN5boost6fibers21promise_uninitializedC1Ev'/>
<use f='boost-1.85.0/libs/fiber/include/boost/fiber/exceptions.hpp' l='138' u='c' c='_ZN5boost6fibers27packaged_task_uninitializedC1Ev'/>
