<inh f='boost-1.85.0/libs/wave/include/boost/wave/cpp_exceptions.hpp' l='84' c='_ZNK5boost4wave13cpp_exception14is_recoverableEv'/>
<def f='boost-1.85.0/libs/wave/include/boost/wave/cpp_exceptions.hpp' l='188' ll='244' type='bool boost::wave::preprocess_exception::is_recoverable() const'/>
