<dec f='boost-1.85.0/libs/exception/include/boost/exception/detail/exception_ptr.hpp' l='193' type='const boost::exception_ptr'/>
<def f='boost-1.85.0/libs/exception/include/boost/exception/detail/exception_ptr.hpp' l='196' ll='199' type='const boost::exception_ptr'/>
<use f='boost-1.85.0/libs/exception/include/boost/exception/detail/exception_ptr.hpp' l='374' u='r' c='_ZN5boost16exception_detail22current_exception_implEv'/>
<use f='boost-1.85.0/libs/exception/include/boost/exception/detail/exception_ptr.hpp' l='380' u='r' c='_ZN5boost16exception_detail22current_exception_implEv'/>
<use f='boost-1.85.0/libs/exception/include/boost/exception/detail/exception_ptr.hpp' l='519' u='r' c='_ZN5boost17current_exceptionEv'/>
<use f='boost-1.85.0/libs/exception/include/boost/exception/detail/exception_ptr.hpp' l='524' u='r' c='_ZN5boost17current_exceptionEv'/>
