<inh f='boost-1.85.0/libs/thread/include/boost/thread/futures/future_error.hpp' l='20' c='boost::future_error'/>
<def f='boost-1.85.0/libs/thread/include/boost/thread/futures/future_error.hpp' l='79' ll='86'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/future.hpp' l='3765' c='_ZN5boost13packaged_task10get_futureEv'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/future.hpp' l='3794' c='_ZN5boost13packaged_taskclEv'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/future.hpp' l='3800' c='_ZN5boost13packaged_task25make_ready_at_thread_exitEv'/>
<size>40</size>
<fun r='_ZN5boost10task_movedC1Ev'/>
