<def f='googletest-1.12.1/googletest/src/gtest.cc' l='2549' ll='2560' type='std::string testing::internal::FormatCxxExceptionMessage(const char * description, const char * location)'/>
<use f='googletest-1.12.1/googletest/src/gtest.cc' l='2646' u='c' c='_ZN7testing8internal35HandleExceptionsInMethodIfSupportedEPT_MS1_FT0_vEPKc'/>
<use f='googletest-1.12.1/googletest/src/gtest.cc' l='2650' u='c' c='_ZN7testing8internal35HandleExceptionsInMethodIfSupportedEPT_MS1_FT0_vEPKc'/>
<doc f='googletest-1.12.1/googletest/src/gtest.cc' l='2548'>// Adds an &quot;exception thrown&quot; fatal failure to the current test.</doc>
