<dec f='include/c++/9/exception' l='76' type='void std::terminate()'/>
<use f='include/c++/9/bits/nested_exception.h' l='71' u='c' c='_ZNKSt16nested_exception14rethrow_nestedEv'/>
<doc f='include/c++/9/exception' l='74'>/** The runtime will call this function if %exception handling must be
   *  abandoned for any reason.  It can also be called by the user.  */</doc>
<use f='include/c++/9/thread' l='139' u='c' c='_ZNSt6threadD1Ev'/>
<use f='include/c++/9/thread' l='152' u='c' c='_ZNSt6threadaSEOS_'/>
<use f='qtbase-6.5.0/src/corelib/global/qassert.cpp' l='123' u='c' c='_Z16qt_check_pointerPKci'/>
<use f='qtbase-6.5.0/src/corelib/global/qassert.cpp' l='136' u='c' c='_Z9qBadAllocv'/>
<use f='qtbase-6.5.0/src/corelib/global/qexceptionhandling.cpp' l='17' u='c' c='_Z10qTerminatev'/>
